# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1082, 626)
        Form.setMaximumSize(QtCore.QSize(1270, 900))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/home_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("border-image: url(:/icon/arkaplan.png) 0 0 0 0 stretch stretch ;")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menuekle_button = QtWidgets.QPushButton(Form)
        self.menuekle_button.setMinimumSize(QtCore.QSize(0, 20))
        self.menuekle_button.setStyleSheet("QPushButton{\n"
"background:qlineargradient(spread:reflect, x1:0, y1:0, x2:0.523, y2:0.522273, stop:0 rgba(252, 128, 128, 0), stop:1 rgba(255, 255, 255, 0));\n"
"font-weight:bold;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(0, 171, 0,100);\n"
"    border:2px solid;\n"
"}")
        self.menuekle_button.setObjectName("menuekle_button")
        self.horizontalLayout.addWidget(self.menuekle_button)
        self.menucikar_button = QtWidgets.QPushButton(Form)
        self.menucikar_button.setMinimumSize(QtCore.QSize(0, 20))
        self.menucikar_button.setStyleSheet("QPushButton{\n"
"background:qlineargradient(spread:reflect, x1:0, y1:0, x2:0.523, y2:0.522273, stop:0 rgba(252, 128, 128, 0), stop:1 rgba(255, 255, 255, 0));\n"
"font-weight:bold;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(0, 171, 0,100);\n"
"    border:2px solid;\n"
"}")
        self.menucikar_button.setObjectName("menucikar_button")
        self.horizontalLayout.addWidget(self.menucikar_button)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        self.odalar = QtWidgets.QGridLayout()
        self.odalar.setContentsMargins(0, 0, -1, 0)
        self.odalar.setHorizontalSpacing(10)
        self.odalar.setVerticalSpacing(0)
        self.odalar.setObjectName("odalar")
        self.no7 = QtWidgets.QPushButton(Form)
        self.no7.setMinimumSize(QtCore.QSize(120, 90))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.no7.setFont(font)
        self.no7.setStyleSheet("QPushButton{\n"
"background:qlineargradient(spread:reflect, x1:0, y1:0, x2:0.523, y2:0.522273, stop:0 rgba(252, 128, 128, 0), stop:1 rgba(255, 255, 255, 0));\n"
"font-weight:bold;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(0, 171, 0,100);\n"
"    border:2px solid;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/bos.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.no7.setIcon(icon1)
        self.no7.setIconSize(QtCore.QSize(100, 100))
        self.no7.setObjectName("no7")
        self.odalar.addWidget(self.no7, 1, 1, 1, 1)
        self.no9 = QtWidgets.QPushButton(Form)
        self.no9.setMinimumSize(QtCore.QSize(120, 90))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.no9.setFont(font)
        self.no9.setStyleSheet("QPushButton{\n"
"background:qlineargradient(spread:reflect, x1:0, y1:0, x2:0.523, y2:0.522273, stop:0 rgba(252, 128, 128, 0), stop:1 rgba(255, 255, 255, 0));\n"
"font-weight:bold;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(0, 171, 0,100);\n"
"    border:2px solid;\n"
"}")
        self.no9.setIcon(icon1)
        self.no9.setIconSize(QtCore.QSize(100, 100))
        self.no9.setCheckable(False)
        self.no9.setAutoRepeat(False)
        self.no9.setAutoRepeatDelay(300)
        self.no9.setObjectName("no9")
        self.odalar.addWidget(self.no9, 1, 3, 1, 1)
        self.no14 = QtWidgets.QPushButton(Form)
        self.no14.setMinimumSize(QtCore.QSize(120, 90))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.no14.setFont(font)
        self.no14.setStyleSheet("QPushButton{\n"
"background:qlineargradient(spread:reflect, x1:0, y1:0, x2:0.523, y2:0.522273, stop:0 rgba(252, 128, 128, 0), stop:1 rgba(255, 255, 255, 0));\n"
"font-weight:bold;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(0, 171, 0,100);\n"
"    border:2px solid;\n"
"}")
        self.no14.setIcon(icon1)
        self.no14.setIconSize(QtCore.QSize(100, 100))
        self.no14.setObjectName("no14")
        self.odalar.addWidget(self.no14, 2, 3, 1, 1)
        self.no5 = QtWidgets.QPushButton(Form)
        self.no5.setMinimumSize(QtCore.QSize(120, 90))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.no5.setFont(font)
        self.no5.setStyleSheet("QPushButton{\n"
"background:qlineargradient(spread:reflect, x1:0, y1:0, x2:0.523, y2:0.522273, stop:0 rgba(252, 128, 128, 0), stop:1 rgba(255, 255, 255, 0));\n"
"font-weight:bold;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(0, 171, 0,100);\n"
"    border:2px solid;\n"
"}")
        self.no5.setIcon(icon1)
        self.no5.setIconSize(QtCore.QSize(100, 100))
        self.no5.setObjectName("no5")
        self.odalar.addWidget(self.no5, 0, 4, 1, 1)
        self.no4 = QtWidgets.QPushButton(Form)
        self.no4.setMinimumSize(QtCore.QSize(120, 90))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.no4.setFont(font)
        self.no4.setStyleSheet("QPushButton{\n"
"background:qlineargradient(spread:reflect, x1:0, y1:0, x2:0.523, y2:0.522273, stop:0 rgba(252, 128, 128, 0), stop:1 rgba(255, 255, 255, 0));\n"
"font-weight:bold;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(0, 171, 0,100);\n"
"    border:2px solid;\n"
"}")
        self.no4.setIcon(icon1)
        self.no4.setIconSize(QtCore.QSize(100, 100))
        self.no4.setObjectName("no4")
        self.odalar.addWidget(self.no4, 0, 3, 1, 1)
        self.no12 = QtWidgets.QPushButton(Form)
        self.no12.setMinimumSize(QtCore.QSize(120, 90))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.no12.setFont(font)
        self.no12.setStyleSheet("QPushButton{\n"
"background:qlineargradient(spread:reflect, x1:0, y1:0, x2:0.523, y2:0.522273, stop:0 rgba(252, 128, 128, 0), stop:1 rgba(255, 255, 255, 0));\n"
"font-weight:bold;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(0, 171, 0,100);\n"
"    border:2px solid;\n"
"}")
        self.no12.setIcon(icon1)
        self.no12.setIconSize(QtCore.QSize(100, 100))
        self.no12.setObjectName("no12")
        self.odalar.addWidget(self.no12, 2, 1, 1, 1)
        self.no10 = QtWidgets.QPushButton(Form)
        self.no10.setMinimumSize(QtCore.QSize(120, 90))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.no10.setFont(font)
        self.no10.setStyleSheet("QPushButton{\n"
"background:qlineargradient(spread:reflect, x1:0, y1:0, x2:0.523, y2:0.522273, stop:0 rgba(252, 128, 128, 0), stop:1 rgba(255, 255, 255, 0));\n"
"font-weight:bold;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(0, 171, 0,100);\n"
"    border:2px solid;\n"
"}")
        self.no10.setIcon(icon1)
        self.no10.setIconSize(QtCore.QSize(100, 100))
        self.no10.setObjectName("no10")
        self.odalar.addWidget(self.no10, 1, 4, 1, 1)
        self.no1 = QtWidgets.QPushButton(Form)
        self.no1.setMinimumSize(QtCore.QSize(120, 90))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.no1.setFont(font)
        self.no1.setStyleSheet("QPushButton{\n"
"background:qlineargradient(spread:reflect, x1:0, y1:0, x2:0.523, y2:0.522273, stop:0 rgba(252, 128, 128, 0), stop:1 rgba(255, 255, 255, 0));\n"
"font-weight:bold;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(0, 171, 0,100);\n"
"    border:2px solid;\n"
"}")
        self.no1.setIcon(icon1)
        self.no1.setIconSize(QtCore.QSize(100, 100))
        self.no1.setObjectName("no1")
        self.odalar.addWidget(self.no1, 0, 0, 1, 1)
        self.no6 = QtWidgets.QPushButton(Form)
        self.no6.setMinimumSize(QtCore.QSize(120, 90))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.no6.setFont(font)
        self.no6.setStyleSheet("QPushButton{\n"
"background:qlineargradient(spread:reflect, x1:0, y1:0, x2:0.523, y2:0.522273, stop:0 rgba(252, 128, 128, 0), stop:1 rgba(255, 255, 255, 0));\n"
"font-weight:bold;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(0, 171, 0,100);\n"
"    border:2px solid;\n"
"}")
        self.no6.setIcon(icon1)
        self.no6.setIconSize(QtCore.QSize(100, 100))
        self.no6.setObjectName("no6")
        self.odalar.addWidget(self.no6, 1, 0, 1, 1)
        self.no11 = QtWidgets.QPushButton(Form)
        self.no11.setMinimumSize(QtCore.QSize(120, 90))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.no11.setFont(font)
        self.no11.setStyleSheet("QPushButton{\n"
"background:qlineargradient(spread:reflect, x1:0, y1:0, x2:0.523, y2:0.522273, stop:0 rgba(252, 128, 128, 0), stop:1 rgba(255, 255, 255, 0));\n"
"font-weight:bold;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(0, 171, 0,100);\n"
"    border:2px solid;\n"
"}")
        self.no11.setIcon(icon1)
        self.no11.setIconSize(QtCore.QSize(100, 100))
        self.no11.setObjectName("no11")
        self.odalar.addWidget(self.no11, 2, 0, 1, 1)
        self.no2 = QtWidgets.QPushButton(Form)
        self.no2.setMinimumSize(QtCore.QSize(120, 90))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.no2.setFont(font)
        self.no2.setStyleSheet("QPushButton{\n"
"background:qlineargradient(spread:reflect, x1:0, y1:0, x2:0.523, y2:0.522273, stop:0 rgba(252, 128, 128, 0), stop:1 rgba(255, 255, 255, 0));\n"
"font-weight:bold;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(0, 171, 0,100);\n"
"    border:2px solid;\n"
"}")
        self.no2.setIcon(icon1)
        self.no2.setIconSize(QtCore.QSize(100, 100))
        self.no2.setObjectName("no2")
        self.odalar.addWidget(self.no2, 0, 1, 1, 1)
        self.no13 = QtWidgets.QPushButton(Form)
        self.no13.setMinimumSize(QtCore.QSize(120, 90))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.no13.setFont(font)
        self.no13.setStyleSheet("QPushButton{\n"
"background:qlineargradient(spread:reflect, x1:0, y1:0, x2:0.523, y2:0.522273, stop:0 rgba(252, 128, 128, 0), stop:1 rgba(255, 255, 255, 0));\n"
"font-weight:bold;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(0, 171, 0,100);\n"
"    border:2px solid;\n"
"}")
        self.no13.setIcon(icon1)
        self.no13.setIconSize(QtCore.QSize(100, 100))
        self.no13.setObjectName("no13")
        self.odalar.addWidget(self.no13, 2, 2, 1, 1)
        self.no3 = QtWidgets.QPushButton(Form)
        self.no3.setMinimumSize(QtCore.QSize(120, 90))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.no3.setFont(font)
        self.no3.setStyleSheet("QPushButton{\n"
"background:qlineargradient(spread:reflect, x1:0, y1:0, x2:0.523, y2:0.522273, stop:0 rgba(252, 128, 128, 0), stop:1 rgba(255, 255, 255, 0));\n"
"font-weight:bold;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(0, 171, 0,100);\n"
"    border:2px solid;\n"
"}")
        self.no3.setIcon(icon1)
        self.no3.setIconSize(QtCore.QSize(100, 100))
        self.no3.setObjectName("no3")
        self.odalar.addWidget(self.no3, 0, 2, 1, 1)
        self.no8 = QtWidgets.QPushButton(Form)
        self.no8.setMinimumSize(QtCore.QSize(120, 90))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.no8.setFont(font)
        self.no8.setStyleSheet("QPushButton{\n"
"background:qlineargradient(spread:reflect, x1:0, y1:0, x2:0.523, y2:0.522273, stop:0 rgba(252, 128, 128, 0), stop:1 rgba(255, 255, 255, 0));\n"
"font-weight:bold;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(0, 171, 0,100);\n"
"    border:2px solid;\n"
"}")
        self.no8.setIcon(icon1)
        self.no8.setIconSize(QtCore.QSize(100, 100))
        self.no8.setObjectName("no8")
        self.odalar.addWidget(self.no8, 1, 2, 1, 1)
        self.gridLayout.addLayout(self.odalar, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background:qlineargradient(spread:reflect, x1:0, y1:0, x2:0.523, y2:0.522273, stop:0 rgba(252, 128, 128, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 1, 1, 1)
        self.hesap_gosterge = QtWidgets.QLCDNumber(Form)
        self.hesap_gosterge.setMaximumSize(QtCore.QSize(16777215, 60))
        self.hesap_gosterge.setStyleSheet("background:qlineargradient(spread:reflect, x1:0, y1:0, x2:0.523, y2:0.522273, stop:0 rgba(252, 128, 128, 0), stop:1 rgba(255, 255, 255, 0));")
        self.hesap_gosterge.setFrameShape(QtWidgets.QFrame.Box)
        self.hesap_gosterge.setFrameShadow(QtWidgets.QFrame.Raised)
        self.hesap_gosterge.setLineWidth(0)
        self.hesap_gosterge.setMidLineWidth(0)
        self.hesap_gosterge.setSmallDecimalPoint(False)
        self.hesap_gosterge.setDigitCount(7)
        self.hesap_gosterge.setMode(QtWidgets.QLCDNumber.Dec)
        self.hesap_gosterge.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.hesap_gosterge.setProperty("value", 0.0)
        self.hesap_gosterge.setProperty("intValue", 0)
        self.hesap_gosterge.setObjectName("hesap_gosterge")
        self.gridLayout.addWidget(self.hesap_gosterge, 2, 1, 1, 1)
        self.menuvebutonlarlayout = QtWidgets.QHBoxLayout()
        self.menuvebutonlarlayout.setObjectName("menuvebutonlarlayout")
        self.Menu = QtWidgets.QScrollArea(Form)
        self.Menu.setMinimumSize(QtCore.QSize(0, 120))
        self.Menu.setMaximumSize(QtCore.QSize(400, 16777215))
        self.Menu.setStyleSheet("background:qlineargradient(spread:reflect, x1:0, y1:0, x2:0.523, y2:0.522273, stop:0 rgba(252, 128, 128, 0), stop:1 rgba(255, 255, 255, 0));")
        self.Menu.setWidgetResizable(True)
        self.Menu.setObjectName("Menu")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 398, 205))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.urun_listesi_QlistWidget = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.urun_listesi_QlistWidget.setFont(font)
        self.urun_listesi_QlistWidget.setStyleSheet("background:rgb(220, 220, 220);\n"
"border:1px solid black;\n"
"")
        self.urun_listesi_QlistWidget.setObjectName("urun_listesi_QlistWidget")
        self.gridLayout_2.addWidget(self.urun_listesi_QlistWidget, 0, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, -1, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.urun_fiyat_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.urun_fiyat_label.setFont(font)
        self.urun_fiyat_label.setStyleSheet("background:qlineargradient(spread:reflect, x1:0, y1:0, x2:0.523, y2:0.522273, stop:0 rgba(252, 128, 128, 0), stop:1 rgba(255, 255, 255, 0));")
        self.urun_fiyat_label.setText("")
        self.urun_fiyat_label.setObjectName("urun_fiyat_label")
        self.verticalLayout_4.addWidget(self.urun_fiyat_label)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.urun_ekle_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.urun_ekle_button.setMinimumSize(QtCore.QSize(60, 15))
        self.urun_ekle_button.setStyleSheet("QPushButton{\n"
"    font-weight:bold;\n"
"    background-color: rgb(85, 255, 255,100);\n"
"    border-radius:30px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(0, 171, 0,100);\n"
"    border:2px solid;\n"
"\n"
"}")
        self.urun_ekle_button.setObjectName("urun_ekle_button")
        self.horizontalLayout_4.addWidget(self.urun_ekle_button)
        self.urun_cikar_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.urun_cikar_button.setMinimumSize(QtCore.QSize(60, 15))
        self.urun_cikar_button.setMaximumSize(QtCore.QSize(60, 16777215))
        self.urun_cikar_button.setStyleSheet("QPushButton{\n"
"    font-weight:bold;\n"
"    background-color: rgb(85, 255, 255,100);\n"
"    border-radius:30px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(0, 171, 0,100);\n"
"    border:2px solid;\n"
"\n"
"}")
        self.urun_cikar_button.setObjectName("urun_cikar_button")
        self.horizontalLayout_4.addWidget(self.urun_cikar_button)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 0, 5, 1, 1)
        self.Menu.setWidget(self.scrollAreaWidgetContents)
        self.menuvebutonlarlayout.addWidget(self.Menu)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gecmislayout = QtWidgets.QVBoxLayout()
        self.gecmislayout.setObjectName("gecmislayout")
        self.odagiris_button = QtWidgets.QPushButton(Form)
        self.odagiris_button.setMinimumSize(QtCore.QSize(0, 20))
        self.odagiris_button.setStyleSheet("QPushButton{\n"
"background:qlineargradient(spread:reflect, x1:0, y1:0, x2:0.523, y2:0.522273, stop:0 rgba(252, 128, 128, 0), stop:1 rgba(255, 255, 255, 0));\n"
"font-weight:bold;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(0, 171, 0,100);\n"
"    border:2px solid;\n"
"\n"
"}")
        self.odagiris_button.setObjectName("odagiris_button")
        self.gecmislayout.addWidget(self.odagiris_button)
        self.kisi_button = QtWidgets.QPushButton(Form)
        self.kisi_button.setMinimumSize(QtCore.QSize(0, 20))
        self.kisi_button.setStyleSheet("QPushButton{\n"
"background:qlineargradient(spread:reflect, x1:0, y1:0, x2:0.523, y2:0.522273, stop:0 rgba(252, 128, 128, 0), stop:1 rgba(255, 255, 255, 0));\n"
"font-weight:bold;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(0, 171, 0,100);\n"
"    border:2px solid;\n"
"}")
        self.kisi_button.setObjectName("kisi_button")
        self.gecmislayout.addWidget(self.kisi_button)
        self.zaman_uzat_pushButton = QtWidgets.QPushButton(Form)
        self.zaman_uzat_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        self.zaman_uzat_pushButton.setStyleSheet("QPushButton{\n"
"background:qlineargradient(spread:reflect, x1:0, y1:0, x2:0.523, y2:0.522273, stop:0 rgba(252, 128, 128, 0), stop:1 rgba(255, 255, 255, 0));\n"
"font-weight:bold;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(0, 171, 0,100);\n"
"    border:2px solid;\n"
"}")
        self.zaman_uzat_pushButton.setObjectName("zaman_uzat_pushButton")
        self.gecmislayout.addWidget(self.zaman_uzat_pushButton)
        self.odafiyat_pushButton = QtWidgets.QPushButton(Form)
        self.odafiyat_pushButton.setStyleSheet("QPushButton{\n"
"background:qlineargradient(spread:reflect, x1:0, y1:0, x2:0.523, y2:0.522273, stop:0 rgba(252, 128, 128, 0), stop:1 rgba(255, 255, 255, 0));\n"
"font-weight:bold;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(0, 171, 0,100);\n"
"    border:2px solid;\n"
"}")
        self.odafiyat_pushButton.setObjectName("odafiyat_pushButton")
        self.gecmislayout.addWidget(self.odafiyat_pushButton)
        self.odacikis_button = QtWidgets.QPushButton(Form)
        self.odacikis_button.setMinimumSize(QtCore.QSize(0, 20))
        self.odacikis_button.setStyleSheet("QPushButton{\n"
"background:qlineargradient(spread:reflect, x1:0, y1:0, x2:0.523, y2:0.522273, stop:0 rgba(252, 128, 128, 0), stop:1 rgba(255, 255, 255, 0));\n"
"font-weight:bold;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(0, 171, 0,100);\n"
"    border:2px solid;\n"
"}")
        self.odacikis_button.setObjectName("odacikis_button")
        self.gecmislayout.addWidget(self.odacikis_button)
        self.verticalLayout_3.addLayout(self.gecmislayout)
        self.menuvebutonlarlayout.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.menuvebutonlarlayout, 1, 0, 2, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.arama_lineEdit = QtWidgets.QLineEdit(Form)
        self.arama_lineEdit.setMinimumSize(QtCore.QSize(0, 22))
        self.arama_lineEdit.setStyleSheet("background:qlineargradient(spread:reflect, x1:0, y1:0, x2:0.523, y2:0.522273, stop:0 rgba(252, 128, 128, 0), stop:1 rgba(255, 255, 255, 0));\n"
"font-weight:bold;")
        self.arama_lineEdit.setText("")
        self.arama_lineEdit.setObjectName("arama_lineEdit")
        self.horizontalLayout_2.addWidget(self.arama_lineEdit)
        self.gridLayout.addLayout(self.horizontalLayout_2, 6, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ekran_scrollArea = QtWidgets.QScrollArea(Form)
        self.ekran_scrollArea.setMinimumSize(QtCore.QSize(300, 140))
        self.ekran_scrollArea.setWidgetResizable(True)
        self.ekran_scrollArea.setObjectName("ekran_scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 298, 155))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ekran_label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ekran_label.setFont(font)
        self.ekran_label.setStyleSheet("background:rgb(220, 220, 220);\n"
"border:1px solid black;\n"
"")
        self.ekran_label.setText("")
        self.ekran_label.setObjectName("ekran_label")
        self.verticalLayout.addWidget(self.ekran_label)
        self.ekran_scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.addWidget(self.ekran_scrollArea)
        self.ekran_scrollArea_2 = QtWidgets.QScrollArea(Form)
        self.ekran_scrollArea_2.setMinimumSize(QtCore.QSize(0, 140))
        self.ekran_scrollArea_2.setWidgetResizable(True)
        self.ekran_scrollArea_2.setObjectName("ekran_scrollArea_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 298, 154))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.ekran_label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.ekran_label_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ekran_label_2.setFont(font)
        self.ekran_label_2.setStyleSheet("background:rgb(220, 220, 220);\n"
"border:1px solid black;\n"
"")
        self.ekran_label_2.setText("")
        self.ekran_label_2.setObjectName("ekran_label_2")
        self.verticalLayout_6.addWidget(self.ekran_label_2)
        self.ekran_scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_5.addWidget(self.ekran_scrollArea_2)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 1, 1, 1)
        self.cikisbuton = QtWidgets.QPushButton(Form)
        self.cikisbuton.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cikisbuton.setFont(font)
        self.cikisbuton.setStyleSheet("QPushButton{\n"
"background:rgb(255, 64, 16);\n"
"font-weight:bold;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(255, 123, 123);\n"
"    border:2px solid;\n"
"}\n"
"")
        self.cikisbuton.setObjectName("cikisbuton")
        self.gridLayout.addWidget(self.cikisbuton, 6, 1, 1, 1)
        self.gecmis_button = QtWidgets.QPushButton(Form)
        self.gecmis_button.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gecmis_button.setFont(font)
        self.gecmis_button.setStyleSheet("QPushButton{\n"
"background:qlineargradient(spread:reflect, x1:0, y1:0, x2:0.523, y2:0.522273, stop:0 rgba(252, 128, 128, 0), stop:1 rgba(255, 255, 255, 0));\n"
"font-weight:bold;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(0, 171, 0,100);\n"
"    border:2px solid;\n"
"}")
        self.gecmis_button.setObjectName("gecmis_button")
        self.gridLayout.addWidget(self.gecmis_button, 4, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "İşletme"))
        self.menuekle_button.setText(_translate("Form", "Menuye ekle"))
        self.menucikar_button.setText(_translate("Form", "Menüden çıkar"))
        self.no7.setText(_translate("Form", "No.7"))
        self.no9.setText(_translate("Form", "No.9"))
        self.no14.setText(_translate("Form", "No.14"))
        self.no5.setText(_translate("Form", "No.5"))
        self.no4.setText(_translate("Form", "No.4"))
        self.no12.setText(_translate("Form", "No.12"))
        self.no10.setText(_translate("Form", "No.10"))
        self.no1.setText(_translate("Form", "No.1"))
        self.no6.setText(_translate("Form", "No.6"))
        self.no11.setText(_translate("Form", "No.11"))
        self.no2.setText(_translate("Form", "No.2"))
        self.no13.setText(_translate("Form", "No.13"))
        self.no3.setText(_translate("Form", "No.3"))
        self.no8.setText(_translate("Form", "No.8"))
        self.label_10.setText(_translate("Form", "Toplam Hesap (TL): "))
        self.urun_ekle_button.setText(_translate("Form", "Ekle"))
        self.urun_cikar_button.setText(_translate("Form", "Çıkar"))
        self.odagiris_button.setText(_translate("Form", "Odaya Giriş"))
        self.kisi_button.setText(_translate("Form", "Kişi bilgileri"))
        self.zaman_uzat_pushButton.setText(_translate("Form", "Zaman uzatma"))
        self.odafiyat_pushButton.setText(_translate("Form", "Oda Fiyatı belirle"))
        self.odacikis_button.setText(_translate("Form", "Odadan Çıkış"))
        self.arama_lineEdit.setPlaceholderText(_translate("Form", "Menü\'de arama..."))
        self.cikisbuton.setText(_translate("Form", "Çıkış"))
        self.gecmis_button.setText(_translate("Form", "Geçmiş"))
import icon_rc
