# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'emin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 140)
        MainWindow.setMinimumSize(QtCore.QSize(300, 140))
        MainWindow.setMaximumSize(QtCore.QSize(320, 170))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.eminmisin_label = QtWidgets.QLabel(self.centralwidget)
        self.eminmisin_label.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.eminmisin_label.setFont(font)
        self.eminmisin_label.setObjectName("eminmisin_label")
        self.verticalLayout.addWidget(self.eminmisin_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.emin_evet_button = QtWidgets.QPushButton(self.centralwidget)
        self.emin_evet_button.setMinimumSize(QtCore.QSize(30, 0))
        self.emin_evet_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self.emin_evet_button.setDefault(False)
        self.emin_evet_button.setObjectName("emin_evet_button")
        self.horizontalLayout.addWidget(self.emin_evet_button)
        self.emin_hayir_button = QtWidgets.QPushButton(self.centralwidget)
        self.emin_hayir_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self.emin_hayir_button.setObjectName("emin_hayir_button")
        self.horizontalLayout.addWidget(self.emin_hayir_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.eminmisin_label.setText(_translate("MainWindow", "Bu işlemi yapmak istediğinize emin misiniz?"))
        self.emin_evet_button.setText(_translate("MainWindow", "Evet"))
        self.emin_hayir_button.setText(_translate("MainWindow", "Hayır"))
