# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kisibilgi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KisiBilgi(object):
    def setupUi2(self, KisiBilgi):
        KisiBilgi.setObjectName("KisiBilgi")
        KisiBilgi.resize(517, 320)
        KisiBilgi.setMinimumSize(QtCore.QSize(400, 200))
        self.centralwidget = QtWidgets.QWidget(KisiBilgi)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.kisi_bilgi_baslik = QtWidgets.QLabel(self.centralwidget)
        self.kisi_bilgi_baslik.setStyleSheet("font-weight:bold;\n"
"text-align: center;\n"
"font-size:15px")
        self.kisi_bilgi_baslik.setObjectName("kisi_bilgi_baslik")
        self.verticalLayout.addWidget(self.kisi_bilgi_baslik)
        self.bilgi_panel_textbrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.bilgi_panel_textbrowser.setStyleSheet("font-weight:bold;\n"
"background-color: rgb(214, 214, 214);")
        self.bilgi_panel_textbrowser.setObjectName("bilgi_panel_textbrowser")
        self.verticalLayout.addWidget(self.bilgi_panel_textbrowser)
        KisiBilgi.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(KisiBilgi)
        self.statusbar.setObjectName("statusbar")
        KisiBilgi.setStatusBar(self.statusbar)

        self.retranslateUi(KisiBilgi)
        QtCore.QMetaObject.connectSlotsByName(KisiBilgi)

    def retranslateUi(self, KisiBilgi):
        _translate = QtCore.QCoreApplication.translate
        KisiBilgi.setWindowTitle(_translate("KisiBilgi", "Kişi Bilgileri"))
        self.kisi_bilgi_baslik.setText(_translate("KisiBilgi", "Kişi Bilgileri"))
        self.bilgi_panel_textbrowser.setHtml(_translate("KisiBilgi", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:400;\"><br /></p></body></html>"))
