# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'odafiyat.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_odafiyat_window(object):
    def setupUi(self, odafiyat_window):
        odafiyat_window.setObjectName("odafiyat_window")
        odafiyat_window.resize(400, 100)
        odafiyat_window.setMinimumSize(QtCore.QSize(400, 100))
        odafiyat_window.setMaximumSize(QtCore.QSize(400, 111))
        self.centralwidget = QtWidgets.QWidget(odafiyat_window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Odafiyat_uyari_label = QtWidgets.QLabel(self.centralwidget)
        self.Odafiyat_uyari_label.setMinimumSize(QtCore.QSize(0, 40))
        self.Odafiyat_uyari_label.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Odafiyat_uyari_label.setFont(font)
        self.Odafiyat_uyari_label.setText("")
        self.Odafiyat_uyari_label.setObjectName("Odafiyat_uyari_label")
        self.verticalLayout.addWidget(self.Odafiyat_uyari_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(15, 0, 15, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.odafiyat_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.odafiyat_lineEdit.setObjectName("odafiyat_lineEdit")
        self.horizontalLayout.addWidget(self.odafiyat_lineEdit)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.odafiyat_degis_pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.odafiyat_degis_pushButton.setFont(font)
        self.odafiyat_degis_pushButton.setObjectName("odafiyat_degis_pushButton")
        self.horizontalLayout.addWidget(self.odafiyat_degis_pushButton)
        self.Odafiyat_cik_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Odafiyat_cik_button.setFont(font)
        self.Odafiyat_cik_button.setObjectName("Odafiyat_cik_button")
        self.horizontalLayout.addWidget(self.Odafiyat_cik_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        odafiyat_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(odafiyat_window)
        self.statusbar.setObjectName("statusbar")
        odafiyat_window.setStatusBar(self.statusbar)

        self.retranslateUi(odafiyat_window)
        QtCore.QMetaObject.connectSlotsByName(odafiyat_window)

    def retranslateUi(self, odafiyat_window):
        _translate = QtCore.QCoreApplication.translate
        odafiyat_window.setWindowTitle(_translate("odafiyat_window", "Oda Fiyatı"))
        self.label.setText(_translate("odafiyat_window", "Yeni Oda Fiyatı : "))
        self.label_2.setText(_translate("odafiyat_window", ".TL"))
        self.odafiyat_degis_pushButton.setText(_translate("odafiyat_window", "Değiştir"))
        self.Odafiyat_cik_button.setText(_translate("odafiyat_window", "Çıkış"))
