# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tarih_uzat.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tarih_uzat(object):
    def setupUi(self, tarih_uzat):
        tarih_uzat.setObjectName("tarih_uzat")
        tarih_uzat.resize(544, 188)
        font = QtGui.QFont()
        font.setPointSize(9)
        tarih_uzat.setFont(font)
        self.centralwidget = QtWidgets.QWidget(tarih_uzat)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.Oda_cikis_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Oda_cikis_label.setFont(font)
        self.Oda_cikis_label.setText("")
        self.Oda_cikis_label.setObjectName("Oda_cikis_label")
        self.verticalLayout.addWidget(self.Oda_cikis_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.yeni_cikis_text = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.yeni_cikis_text.setFont(font)
        self.yeni_cikis_text.setObjectName("yeni_cikis_text")
        self.horizontalLayout.addWidget(self.yeni_cikis_text)
        self.new_date_edit = QtWidgets.QDateEdit(self.centralwidget)
        self.new_date_edit.setObjectName("new_date_edit")
        self.horizontalLayout.addWidget(self.new_date_edit)
        self.degistir_pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.degistir_pushButton.setFont(font)
        self.degistir_pushButton.setObjectName("degistir_pushButton")
        self.horizontalLayout.addWidget(self.degistir_pushButton)
        self.tarih_uzat_cikis_pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tarih_uzat_cikis_pushButton.setFont(font)
        self.tarih_uzat_cikis_pushButton.setObjectName("tarih_uzat_cikis_pushButton")
        self.horizontalLayout.addWidget(self.tarih_uzat_cikis_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.degistirildi_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(9)
        self.degistirildi_label.setFont(font)
        self.degistirildi_label.setText("")
        self.degistirildi_label.setObjectName("degistirildi_label")
        self.verticalLayout.addWidget(self.degistirildi_label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        tarih_uzat.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(tarih_uzat)
        self.statusbar.setObjectName("statusbar")
        tarih_uzat.setStatusBar(self.statusbar)

        self.retranslateUi(tarih_uzat)
        QtCore.QMetaObject.connectSlotsByName(tarih_uzat)

    def retranslateUi(self, tarih_uzat):
        _translate = QtCore.QCoreApplication.translate
        tarih_uzat.setWindowTitle(_translate("tarih_uzat", "Tarih uzatma"))
        self.yeni_cikis_text.setText(_translate("tarih_uzat", "Yeni Çıkış Tarihi : "))
        self.degistir_pushButton.setText(_translate("tarih_uzat", "Değiştir"))
        self.tarih_uzat_cikis_pushButton.setText(_translate("tarih_uzat", "Çıkış"))
